[tool.gdsfactoryplus]
name = "demo"

[tool.gdsfactoryplus.pdk]
tag = "cspdk"
name = "cspdk.si220"

[tool.gdsfactoryplus.drc]
threads = 8

[tool.basedpyright]
reportMissingImports = true
reportMissingTypeStubs = false
reportUnknownMemberType = false
reportUnusedCallResult = false
pythonPlatform = "Linux"
