[tool.dodesign]
name = "demo"

[tool.dodesign.pdk]
tag = "generic-prod"
name = "cspdk.si220"
path = "cspdk"

[tool.basedpyright]
reportMissingImports = true
reportMissingTypeStubs = false
reportUnknownMemberType = false
reportUnusedCallResult = false
pythonPlatform = "Linux"
